name: gpax
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip>=20.3.3
  - conda>=4.9.2
  - pip:
    - glfw==2.5.0
    - gpy==1.10.0
    - gym==0.22.0
    - h5py==3.6.0
    - imageio==2.14.1
    - matplotlib==3.5.1
    - numpy==1.21.5
    - opencv-python==4.5.5.62
    - pillow==9.0.0
    - pybind11==2.9.0
    - pygifsicle==1.0.5
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
    - torch==1.10.2
    - ttkbootstrap==1.5.1
    - typing==3.7.4.3
    - --find-links https://storage.googleapis.com/jax-releases/jax_releases.html
    - -r requirements.txt