constrain_outputs: false
mutation: standard
n_evals_per_individual: 1 #5
n_individuals: 100
n_parallel_runs: 1
nan_replacement: -100000.0
distance: false
p_mut_functions: 0.1
recursive: false
use_input_constants: true
saving_interval: 100
seed: [ 0,1,2,3,4 ]
train_size: 0.8
selection:
  elite_size: 10
  tour_size: 3
  type: tournament
survival: truncation

nested0:
  - n_nodes: 50
    p_mut_inputs: 0.1
    p_mut_outputs: 0.3
    solver: cgp
  - n_extra_registers: 10
    n_rows: 35
    p_mut_lhs: 0.3
    p_mut_rhs: 0.1
    solver: lgp
n_evaluations: 500_000
problem: [feynman_13_61, feynman_42_43_48, feynman_13_61_62_70_77_100]
early_stop: false
